name: Pipeline Python Básica

on: [push]

jobs:
  python-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      - name: Validar ambiente e executar script
        run: |
          echo "Verificando versão instalada:"
          python --version
          
          echo "Listando pacotes instalados (pip):"
          pip list
          
          echo "Executando um print via Python:"
          python -c "print('Sucesso! O Python rodou dentro do GitHub Actions.')"
